version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:8080
functions:
  controlplane:
    lang: python3-flask
    handler: ./controlplane
    image: koogordo/modelexecute-controlplane:latest
    environment:
      DB_PASSWORD: postgres
      ENVIRONMENT: local
      MODEL_NAME: wine-quality
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 5
      com.openfaas.scale.zero: true
      com.openfaas.scale.zero-duration: 15m
      com.openfaas.scale.type: capacity
      com.openfaas.scale.target: 50
      com.openfaas.scale.target-proportion: 0.90
  executor:
    lang: python3-flask
    handler: ./executor
    image: koogordo/modelexecute-executor:latest
    environment:
      DB_PASSWORD: postgres
      ENVIRONMENT: local
      MODEL_NAME: wine-quality
    labels:
      com.openfaas.scale.zero: true
      com.openfaas.scale.zero-duration: 15m
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 10
      com.openfaas.scale.type: capacity
      com.openfaas.scale.target: 10
      com.openfaas.scale.target-proportion: 0.90
  partitioner:
    lang: python3-flask
    handler: ./partitioner
    image: koogordo/modelexecute-partitioner:latest
    environment:
      DB_PASSWORD: postgres
      ENVIRONMENT: local
      MODEL_NAME: wine-quality
    labels:
      com.openfaas.scale.zero: true
      com.openfaas.scale.zero-duration: 15m
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 10
      com.openfaas.scale.type: capacity
      com.openfaas.scale.target: 10
      com.openfaas.scale.target-proportion: 0.90
