version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  driver:
    lang: python3
    handler: ./driver
    image:  koogordo/modelexecute-driver:latest
    environment:
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      LOCALHOST: host.minikube.internal
  worker:
    lang: python3
    handler: ./worker
    image:  koogordo/modelexecute-worker:latest
    environment:
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      LOCALHOST: host.minikube.internal
